//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fertitec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.Orden_Producto = new HashSet<Orden_Producto>();
        }
    
        public int idOrden { get; set; }
        public System.DateTime fecha_creacion_ { get; set; }
        public string num_confirmacion { get; set; }
        public decimal Total { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> id_dirEnt { get; set; }
        public Nullable<int> idPaqueteria { get; set; }
        public string num_guia { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Paqueterias Paqueterias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden_Producto> Orden_Producto { get; set; }
    }
}
