//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FertilizantesV1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.dirEntrega = new HashSet<dirEntrega>();
            this.orden = new HashSet<orden>();
        }
    
        public int id_cliente { get; set; }
        [Display(Name = "Nombre completo")]
        [Required(ErrorMessage ="Debe ser mayor o menor")]
        public string nombre { get; set; }
        public string email { get; set; }
        [Display(Name = "Calle y Num")]
        public string calle_t { get; set; }
        [Display(Name = "Colonia")]
        public string colonia_t { get; set; }
        [Display(Name = "Estado")]
        public string estado_t { get; set; }
        [Display(Name = "No. Tarjeta de Crédito")]
        [Required(ErrorMessage = "Requerido")]
        [Range(100000000000, 9999999999999999, ErrorMessage = "Debe ser entre 12 y 16 digitos")]
        public string num_tarj_cred { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dirEntrega> dirEntrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden> orden { get; set; }
    }
}
