//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FertilizantesV1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class paqueteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paqueteria()
        {
            this.orden = new HashSet<orden>();
        }

        [Display(Name = "Identificador de la paquetería")]
        public int id_paqueteria { get; set; }
        [Display(Name = "Nombre de la paquetería")]
        public string nombre { get; set; }
        [Display(Name = "RFC de la paquetería")]
        public string rfc { get; set; }
        [Display(Name = "Teléfono de la paquetería")]
        public string tel { get; set; }
        [Display(Name = "Sitio web de la paquetería")]
        public string web { get; set; }
        [Display(Name = "Dirección de la paquetería")]
        public string direccion { get; set; }
        [Display(Name = "Nombre del encargado de la paquetería")]
        public string contacto { get; set; }
        [Display(Name = "Teléfono del encargado de la paquetería")]
        public string tel_contacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden> orden { get; set; }
    }
}
