//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatFertilizantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int IdCliente { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string calle { get; set; }
        public string colonia { get; set; }
        public Nullable<int> cp { get; set; }
        public string estado { get; set; }
        public string num_tarjeta { get; set; }
    }
}
