//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatFertilizantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int Idcomentario { get; set; }
        public string comentario { get; set; }
        public string respuesta { get; set; }
        public string status { get; set; }
        public Nullable<int> idproducto { get; set; }
        public Nullable<int> idcliente { get; set; }
    }
}
